config/routes.rb
Cookbook::Application.routes.draw do
  match 'admin', :to => 'access#menu'

  resources :admin_users

  get "ajax/subcategories"
  get "ajax/recipes"
  get "ajax/search_ajax"
  get "ajax/search"
  get "public/public_search"

  resources :recipes
  resources :categories
  root :to => "public#app"

     match 'admin' => 'categories#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    belongs_to :subcategory

    has_attached_file :recipe_image

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.xml
  layout 'admin'
  #before_filter :confirm_admin_logged_in


  def index
    @recipe = Recipe.find(params[:id])

  end

  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new
    @categories = Category.order('category ASC').all
    @subcategories = Subcategory.order('subcategory ASC').find_all_by_category_id(4)
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipe }
      format.json  { render :json => @subcategories }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
    @categories = Category.order('category ASC').all
    @subcategories = Subcategory.order('subcategory ASC').find_all_by_id(params[:subcategory])
  end

  # POST /recipes
  # POST /recipes.xml
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to(:controller => 'recipes',:id=>@recipe.id) }
        format.xml  { render :xml => @recipe, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to(@recipe, :notice => 'Recipe was successfully updated.') }
        format.xml  { head :ok }
        format.js   { render :nothing => true }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
        format.js   { render :nothing => false }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => 'categories', :notice => 'Recipe Deleted Successfully') }
      format.js   { render :nothing => true }

    end
  end


end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br />
    <%= f.text_field :subcategory %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :directions %><br />
    <%= f.text_area :directions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>New recipe</h1>

<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">

    <label for="category"></label>
    <select name="category" id="category">
      <% @categories.each do |category| %>
      <option value="<%= category.id %>"><%= category.category %></option>
      <% end %>
    </select>
  </div>
  <div class="field">
    <%= f.label :subcategory_id %><br />
    <%= select( :recipe, "subcategory_id", @subcategories.map {|u| [u.subcategory,u.id]}) %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :recipe_image %><br />
    <%= f.file_field :recipe_image %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :directions %><br />
    <%= f.text_area :directions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', recipes_path %>

app/views/recipes/list.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Subcategory</th>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Ingredients</th>
    <th>Directions</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.category %></td>
    <td><%= recipe.subcategory %></td>
    <td><%= recipe.title %></td>
    <td><%= recipe.subtitle %></td>
    <td><%= auto_link(recipe.ingredients) %></td>
    <td><%= auto_link(recipe.directions) %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_image %><br />
    <%= f.file_field :recipe_image %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :directions %><br />
    <%= f.text_area :directions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div id="bd" class="recipe-page">
    <div class="wrapper">
        <div id="bread-crumbs">
            <ul>
                <li><h3><a href="/categories">Admin</a></h3></li>
                <li><h3><%= link_to(@recipe.subcategory.category.category, {:controller => 'subcategories', :action => 'index', :id => @recipe.subcategory.category.id}) %></h3></li>
                <li><h3><%= link_to(@recipe.subcategory.subcategory, {:controller => 'subcategories',:action => 'show', :id => @recipe.subcategory.id}) %></h3></li>
            </ul>
        </div>
        <div id="main-edit-wrapper">
            <ul>
                <li>
                    <span id="delete-recipe" class="button-wrapper">
                        <a href="#" class="button"><i>x</i>Delete</a>
                    </span>

                </li>
            </ul>
        </div>
        <div id="recipe-wrapper">
            <div class="hd">
                <span class="button-wrapper edit recipe-hd"><span class="button"><i></i>Edit</span></span>
                <h2 id="recipe-title"><%= @recipe.title.html_safe %></h2>
                <h3 id="recipe-subtitle"><%= @recipe.subtitle.html_safe %></h3>

            </div>

            <div class="bd">
                <% form_for @recipe, :html => {:action => 'update', :method => 'put', :id => 'recipe-image-submit',  :multipart => true, :remote => true } do |f| %>
                    <%= f.file_field :recipe_image %>
                    <button id="recipe-image-submit" class="button-wrapper" name="commit" type="submit"><span class="button">Upload Image</span></button>
                <% end %>
                <span class="button-wrapper edit recipe-bd"><span class="button"><i></i>Edit</span></span>
                <div id="recipe-ingredients"><%= @recipe.ingredients.html_safe %></div>
                <div id="recipe-directions"><%= @recipe.directions.html_safe %></div>
            </div>
        </div>

        <div id="tags-wrapper">
            <h4>Tags</h4>

            <div id="tags">
            </div>
        </div>
    </div>

</div>
<% content_for :javascript do %>
    <script type="text/javascript">
        /*******  TITLE UPDATE *******/
        $('.recipe-hd').live('click', function(){
            var title = $('#recipe-title').text();
            var subtitle = $('#recipe-subtitle').text();
            var form = '<%= form_for @recipe, :html => {:action => 'update', :method => 'put', :id => 'title-submit', :remote => true} do %><input id="recipe_title" name="recipe[title]" size="30" value="'+title+'"><input id="recipe_subtitle" name="recipe[subtitle]" size="30" type="text" value="'+subtitle+'"><button id="recipe_submit" class="button-wrapper" name="commit" type="submit"><span class="button">Update Title</span></button><button class="button-wrapper" id="title-cancel"><span class="button">Cancel</span></button><% end %>';
            $(this).parent().html(form);

            $('#title-cancel').click(function(){
                $('#recipe-wrapper .hd').html('<span class="button-wrapper edit recipe-hd"><span class="button"><i></i>Edit</span></span><h2 id="recipe-title">'+title+'</h2><h3 id="recipe-subtitle">'+subtitle+'</h3>');
            });

        });
        $("#title-submit").live("ajax:success", function(event, data, status, xhr) {
          var title = $('#recipe_title').val();
          var subtitle = $('#recipe_subtitle').val();
          $('#recipe-wrapper .hd').html('<span class="button-wrapper edit recipe-hd"><span class="button"><i></i>Edit</span></span><h2 id="recipe-title">'+title+'</h2><h3 id="recipe-subtitle">'+subtitle+'</h3>');
        });


        /*******  RECIPE UPDATE *******/

        $('.recipe-bd').live('click', function(){
            var ingredients = $('#recipe-ingredients').html();
            var directions = $('#recipe-directions').html();
            var form = '<%= form_for @recipe, :html => {:action => 'update', :method => 'put', :id => 'recipe-submit', :remote => true} do %><textarea id="recipe_ingredients" name="recipe[ingredients]">'+ingredients+'</textarea><textarea id="recipe_directions" name="recipe[directions]">'+directions+'</textarea><button id="recipe_submit" class="button-wrapper" name="commit" type="submit" ><span class="button">Update Recipe</span></button><button class="button-wrapper" id="recipe-cancel"><span class="button">Cancel Recipe</span></button><% end %>';
            $(this).parent().html(form);


            $('#recipe-cancel').click(function(){
                $('#recipe-wrapper .bd').html('<span class="button-wrapper edit recipe-bd"><span class="button"><i></i>Edit</span></span><div id="recipe-ingredients"><p>'+ingredients+'</p></div><div id="recipe-directions"><p>'+directions+'</p></div>');
            });
        });
        $("#recipe-submit").live("ajax:success", function(event, data, status, xhr) {
          var ingredients = $('#recipe_ingredients').val();
          var directions = $('#recipe_directions').val();
          $('#recipe-wrapper .bd').html('<span class="button-wrapper edit recipe-bd"><span class="button"><i></i>Edit</span></span><div id="recipe-ingredients"><p>'+ingredients+'</p></div><div id="recipe-directions"><p>'+directions+'</p></div>');
        });


        /*******  RECIPE IMAGE UPDATE *******/
//
//        $('.recipe-bd').live('click', function(){
//            var ingredients = $('#recipe-ingredients').html();
//            var directions = $('#recipe-directions').html();
//            var form = '<%= form_for @recipe, :html => {:action => 'update', :method => 'put', :id => 'recipe-submit', :remote => true} do %><textarea id="recipe_ingredients" name="recipe[ingredients]">'+ingredients+'</textarea><textarea id="recipe_directions" name="recipe[directions]">'+directions+'</textarea><button id="recipe_submit" class="button-wrapper" name="commit" type="submit" ><span class="button">Update Recipe</span></button><button class="button-wrapper" id="recipe-cancel"><span class="button">Cancel Recipe</span></button><% end %>';
//            $(this).parent().html(form);
//
//
//            $('#recipe-cancel').click(function(){
//                $('#recipe-wrapper .bd').html('<span class="button-wrapper edit recipe-bd"><span class="button"><i></i>Edit</span></span><div id="recipe-ingredients"><p>'+ingredients+'</p></div><div id="recipe-directions"><p>'+directions+'</p></div>');
//            });
//        });
        $("#recipe-image-submit").live("ajax:success", function(event, data, status, xhr) {
//          var ingredients = $('#recipe_ingredients').val();
//          var directions = $('#recipe_directions').val();
//          $('#recipe-wrapper .bd').html('<span class="button-wrapper edit recipe-bd"><span class="button"><i></i>Edit</span></span><div id="recipe-ingredients"><p>'+ingredients+'</p></div><div id="recipe-directions"><p>'+directions+'</p></div>');
        });

        
        /*******  DELETE RECIPE *******/
        $('#delete-recipe').click(function(e){
            e.preventDefault();
            $('#bd').append('<div class="lb-content"><p>Are you sure you want to delete this recipe?</p> <div class="ft"><span class="button-wrapper"><%= link_to({:action => 'destroy', :id => @recipe.id}, :method => 'delete', :class => 'button', :id => 'delete-recipe-confirm') do %><i>x</i>Delete<% end %></span><span class="button-wrapper delete-cancel"><a class="button">Cancel</a></span></div></div>');
            $('.delete-cancel').click(function(){
                $('.lb-content').css('display','none');
            });
            
        });



    </script>
<% end %>