config/routes.rb
Cookbook::Application.routes.draw do
  match 'admin', :to => 'access#menu'

  resources :admin_users

  get "ajax/subcategories"
  get "ajax/recipes"
  get "ajax/search_ajax"
  get "ajax/search"
  get "public/public_search"

  resources :recipes
  resources :categories
  root :to => "public#app"

     match 'admin' => 'categories#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/admin_user.rb
require 'digest/sha1'
class AdminUser < ActiveRecord::Base
  attr_accessor :password








  before_save :create_hashed_password
  after_save :clear_password

  attr_protected :hashed_password, :salt

  def self.authenticate(email="", password="")
    user = AdminUser.find_by_email(email)

    if user && user.password_match?(password)
      return user
    else
      return false
    end
  end

  def password_match?(password="")
    hashed_password == AdminUser.hash_with_salt(password, salt)
  end


  def self.make_salt(email="")
    Digest::SHA1.hexdigest("swearwording #{email} sdfd312asdfbs12Ssd #{Time.now} bdigejdmg333d3dbwq122")
  end
  def self.hash_with_salt(hashed_password='', salt='')
    Digest::SHA1.hexdigest("agaeg22 #{salt} ogese53bdfb4s7b2d8n #{hashed_password}")
  end

  private

  def create_hashed_password
    unless password.blank?
      self.salt = AdminUser.make_salt(email) if salt.blank?
      self.hashed_password = AdminUser.hash_with_salt(password,salt)
    end
  end

  def clear_password
    self.password = nil
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  # GET /admin_users
  # GET /admin_users.xml
  def index
    @admin_users = AdminUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_users }
    end
  end

  # GET /admin_users/1
  # GET /admin_users/1.xml
  def show
    @admin_user = AdminUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_user }
    end
  end

  # GET /admin_users/new
  # GET /admin_users/new.xml
  def new
    @admin_user = AdminUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_user }
    end
  end

  # GET /admin_users/1/edit
  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  # POST /admin_users
  # POST /admin_users.xml
  def create
    @admin_user = AdminUser.new(params[:admin_user])

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to(@admin_user, :notice => 'Admin user was successfully created.') }
        format.xml  { render :xml => @admin_user, :status => :created, :location => @admin_user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin_users/1
  # PUT /admin_users/1.xml
  def update
    @admin_user = AdminUser.find(params[:id])

    respond_to do |format|
      if @admin_user.update_attributes(params[:admin_user])
        format.html { redirect_to(@admin_user, :notice => 'Admin user was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_users/1
  # DELETE /admin_users/1.xml
  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy

    respond_to do |format|
      format.html { redirect_to(admin_users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password%>
    <%= f.password_field :password, :type => "password" %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin_users/edit.html.erb
<h1>Editing admin_user</h1>

<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <label for="old-password">Old Password</label>
    <input type="password" id="old-password" name="password">
    <label for="new-password">Old Password</label>
    <input type="password" id="new-password" name="password">
    <label for="new-password-repeat">Old Password</label>
    <input type="password" id="new-password-repeat" name="password">

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', @admin_user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin_users/index.html.erb
<h1>Listing admin_users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_users.each do |admin_user| %>
  <tr>
    <td><%= admin_user.email %></td>
    <td><%= link_to 'Show', admin_user %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(admin_user) %></td>
    <td><%= link_to 'Destroy', admin_user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin user', new_admin_user_path %>

app/views/admin_users/new.html.erb
<h1>New admin_user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin_users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_user_path(@admin_user) %> |
<%= link_to 'Back', admin_users_path %>